---
- name: Update Homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - homebrew

- name: Disable Homebrew Analytics
  shell: brew analytics off

- name: Copy Brewfile
  copy:
    src: .Brewfile
    dest: ~/.Brewfile
    mode: 0644
  tags:
    - homebrew

- name: Copy Git Configuration
  template:
    src: .gitconfig.j2
    dest: ~/.gitconfig
    mode: 0600
  tags:
    - homebrew
    - git

- name: Copy Git Ignores
  copy:
    src: .gitignore
    dest: ~/.gitignore
    mode: 0600
  tags:
    - homebrew
    - git

  - name: AppStore Login
    shell: "mas signin {{ email }}"
    tags:
      - homebrew

  - name: Install Homebrew Packages
    shell: brew bundle --file ~/.Brewfile
