---
- name: Install Homebrew Taps
  homebrew_tap:
    name: homebrew/homebrew-php
    state: present
  tags:
    - homebrew

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - homebrew

- name: Disable Homebrew Analytics
  shell: brew analytics off
