---
- name: Install VCS
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - mercurial
  tags:
    - vcs

- name: Copy VCS Configurations
  template:
    src: "{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: 0600
  with_items:
    - { src: '.gitconfig.j2', dest: '.gitconfig' }
    - { src: '.hgrc.j2', dest: '.hgrc' }
  tags:
    - vcs

- name: Copy Global Git Ignores
  copy:
    src: .gitignore
    dest: ~/.gitignore
    mode: 0600
  tags:
    - vcs