---
- name: Install Shells And Enhancements
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - bash
    - bash-completion
    - zsh
    - zsh-autosuggestions
  tags:
    - shell

- name: Add Custom Shells
  lineinfile:
    dest: /etc/shells
    line: "{{ item }}"
    backup: yes
  become: yes
  with_items:
    - /usr/local/bin/bash
    - /usr/local/bin/zsh
  tags:
    - shell

- name: Clone Shell Themes
  git:
    repo: "{{ item.repo }}"
    dest: "~/.zsh/{{ item.dest }}"
    depth: "{{ item.depth | default('') }}"
    update: yes
  with_items:
    - repo: git@github.com:sindresorhus/pure.git
      dest: pure
    - repo: git@github.com:romkatv/powerlevel10k.git
      dest: powerlevel10k
      depth: 1

- name: Change User Default Shell
  user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/local/bin/{{ shell }}"
  become: yes
  tags:
    - shell

- name: Copy Shell Configuration Files
  copy:
    src: files/
    dest: ~/
    mode: 0600
  tags:
    - shell

- name: Make SSH Directory
  file:
    src: ~/.ssh
    state: directory
    mode: 0700
  when: ssh_config is defined
  tags:
    - shell

- name: Copy SSH Configuration
  template:
    src: config.j2
    dest: ~/.ssh/config
    mode: 0600
  when: ssh_config is defined
  tags:
    - shell
