---
- name: Install Shells And Enhancements
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    # - bash
    - bash-completion
    # - zsh
    - zsh-autosuggestions
  tags:
    - shell

#- name: Add Custom Shells
#  lineinfile:
#    dest: /etc/shells
#    line: "{{ item }}"
#    backup: yes
#  become: yes
#  with_items:
#    - /usr/local/bin/bash
#    - /usr/local/bin/zsh
#  tags:
#    - shell

- name: Install Shell Theme
  shell: brew install pure

#- name: Change User Default Shell
#  user:
#    name: "{{ ansible_user_id }}"
#    shell: "/usr/local/bin/{{ shell }}"
#  become: yes
#  tags:
#    - shell

- name: Copy Shell Configuration Files
  copy:
    src: files/
    dest: ~/
    mode: 0600
  tags:
    - shell

- name: Make SSH Directory
  file:
    src: ~/.ssh
    state: directory
    mode: 0700
  when: ssh_config is defined
  tags:
    - shell

- name: Copy SSH Configuration
  template:
    src: config.j2
    dest: ~/.ssh/config
    mode: 0600
  when: ssh_config is defined
  tags:
    - shell
