---
- name: Install Shell Enhancements
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - bash
    - bash-completion
  tags:
    - shell

- name: Add Shell
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/bash
    backup: yes
  become: yes
  tags:
    - shell

- name: Change User Shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/bash
  become: yes
  tags:
    - shell

- name: Copy Bash Configuration
  copy:
    src: files/
    dest: ~/
    mode: 0600
  tags:
    - shell

- name: Make SSH Directory
  file:
    src: ~/.ssh
    state: directory
    mode: 0700
  when: ssh_config is defined
  tags:
    - shell

- name: Copy SSH Configuration
  template:
    src: config.j2
    dest: ~/.ssh/config
    mode: 0600
  when: ssh_config is defined
  tags:
    - shell
