---
- name: Install SleepWatcher
  homebrew:
    name: sleepwatcher
    state: latest
  tags:
    - sleepwatcher

- name: Copy SleepWatcher Configuration
  template:
    src: "{{ item }}"
    dest: ~/{{ item | basename | regex_replace('\.j2','') }}
    mode: 0744
  with_items:
    - .sleep.j2
    - .wakeup.j2
  tags:
    - sleepwatcher

- name: Start SleepWatcher Service
  shell: brew services start sleepwatcher
  become_user: "{{ ansible_user_id }}"
  tags:
    - sleepwatcher

- name: Create SleepWatcher Log Directory
  file:
    path: "{{ sleepwatcher.log | dirname }}"
    state: directory
    mode: 0751
  tags:
    - sleepwatcher

- name: Create SleepWatcher Log File
  file:
    path: "{{ sleepwatcher.log }}"
    state: touch
    mode: 0644
  tags:
    - sleepwatcher
