---
- name: Install Utilities
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - tree
    - ncdu
    - ack
    - p7zip
    - archey
    - neofetch
    - httpie
    - tmux
    - htop
    - rename
    - jhead
    - youtube-dl
    - mas
    - trash
    - fdupes
    - nmap
    - wget
    - blueutil
    - jq
  tags:
    - utilities

- name: Install Homebrew Remove Tree
  shell: brew tap beeftornado/rmtree

- name: Download FFMpeg Binary Archive
  get_url:
    url: https://ffmpeg.zeranoe.com/builds/macos64/static/ffmpeg-latest-macos64-static.zip
    dest: /tmp
  tags:
    - utilities
    - ffmpeg

# https://unix.stackexchange.com/questions/14120/extract-only-a-specific-file-from-a-zipped-archive-to-a-given-directory/57522
- name: Unarchive FFMpeg Binaries
  shell: unzip -jo "/tmp/ffmpeg-latest-macos64-static.zip" "ffmpeg-latest-macos64-static/bin/*" -d /usr/local/bin
  become: yes
  tags:
    - utilities
    - ffmpeg

- name: Update FFMpeg Binary Permissions
  file:
    path: "/usr/local/bin/{{ item }}"
    owner: root
    group: wheel
    mode: 0755
  with_items:
    - ffmpeg
    - ffprobe
    - ffplay
  become: yes
  tags:
    - utilities
    - ffmpeg

- name: Remove FFMpeg Archive
  file:
    path: /tmp/ffmpeg-latest-macos64-static.zip
    state: absent
  tags:
    - utilities
    - ffmpeg
