---
- name: Install Applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - keepingyouawake
    - macdown
    - vagrant
    - virtualbox
    - virtualbox-extension-pack
    - visual-studio-code
    - sequel-pro
    - docker
    - sourcetree
    - google-chrome
    - firefox
    - steam
    - transmission
    - vlc
    - calibre
    - visual-studio-code
    - transmit
    - dropbox
    - the-unarchiver
    - spotify
    - skype
    - phpstorm
    - kap
    - clamxav
    - coconutbattery
    - github
    - sublime-text
    - mullvadvpn
    - table-tools
    - namechanger
    - etcher
    - oversight
    - ext4fuse
  tags:
    - apps

- name: AppStore Login
  shell: "mas signin {{ email }}"
  tags:
    - apps
    - appstore

- name: Install AppStore Applications
  shell: "mas install {{ item }}"
  with_items:
    - 443126292 # TrashMe
    - 441258766 # Magnet
    - 1063631769 # Medis
    - 880001334 # Reeder 3
    - 409201541 # Pages
    - 409203825 # Numbers
    - 409183694 # Keynote
  tags:
    - apps
    - appstore
