---
- name: Install Applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - keepingyouawake
    - macdown
    - vagrant
    - virtualbox
    - virtualbox-extension-pack
    - visual-studio-code
    - sequel-pro
    - docker
    - sourcetree
    - google-chrome
    - firefox
    - steam
    - transmission
    - vlc
    - calibre
    - visual-studio-code
    - transmit
    - dropbox
    - the-unarchiver
    - spotify
    - skype
    - phpstorm
    - kap
    - clamxav
    - coconutbattery
    - github
    - sublime-text
    - mullvadvpn
    - table-tools
    - namechanger
    - etcher
    - oversight
  tags:
    - apps
