---
- name: Check Photo Library Exists
  stat:
    path: "~/Pictures/Photos Library.photoslibrary/Masters/"
  register: photo_library
  tags:
    - macos
    - photos

- name: Symlink Photos Library
  file:
    src: "~/Pictures/Photos Library.photoslibrary/Masters/"
    dest: "~/Pictures/Photos Library Raw"
    state: link
  when: photo_library.stat.exists
  tags:
    - macos
    - photos

- name: Copy Mac OS Script
  template:
    src: .macos.j2
    dest: /tmp/macos.sh
    mode: 0700
  tags:
    - macos

- name: Run Mac OS Script
  shell: /bin/bash /tmp/macos.sh
  tags:
    - macos

- name: Remove Mac OS Script
  file:
    path: /tmp/macos.sh
    state: absent
  tags:
    - macos
