---
- hosts: localhost
  vars_files:
    - vars/vars.yml
  pre_tasks:
    - name: Disable macOS Gatekeeper
      shell: sudo spctl --master-disable
  roles:
    - homebrew
    - shell
    - utilities
    - vcs
    - apps
    - languages
    - fonts
    - macos
    - cleanup
  post_tasks:
    - name: Enable macOS Gatekeeper
      shell: sudo spctl --master-enable
