---
- hosts: localhost
  vars_files:
    - vars/vars.yml
  roles:
    - homebrew
    - shell
    - utilities
    - vcs
    - sleepwatcher
    - apps
    - php
    - ruby
    - go
    - security
    - fonts
    - macos
    - cleanup
