---
- hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Hombrew Taps
      homebrew_tap:
        name: homebrew/homebrew-php
        state: present
      tags:
        - homebrew

    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      tags:
        - homebrew

    - name: Install Shell Enhancements
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - bash
        - bash-completion
      tags:
        - homebrew
        - shell

    - name: Add Shell
      lineinfile:
        dest: /etc/shells
        line: /usr/local/bin/bash
        backup: yes
      become: yes
      tags:
        - shell

    - name: Change User Shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/local/bin/bash
      tags:
        - shell

    - name: Install VCS
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - mercurial
        - svn
      tags:
        - homebrew
        - vcs

    - name: Install Utilities
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - tree
        - ncdu
        - mosh
        - ack
        - p7zip
        - archey
        - neofetch
        - httpie
        - sleepwatcher
        - tmux
        - htop
        - rename
        - php71
      tags:
        - homebrew

    - name: Symlink SRM
      shell: brew link --force srm

    - name: Install WGet
      homebrew:
        name: wget
        options: with-iri
        state: latest
      tags:
        - homebrew

    - name: Install Cask Applications
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - keepingyouawake
        - macdown
        - vagrant
        - virtualbox
        - virtualbox-extension-pack
      tags:
        - homebrew
        - cask

    - name: Install RBEnv
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - ruby-build
        - rbenv
      tags:
        - ruby

    - name: Install Ruby
      shell: rbenv install --skip-existing {{ ruby_version }} && rbenv global {{ ruby_version }}
      tags:
        - ruby

    - name: Install Golang
      homebrew:
        name: go
        state: latest
     tags:
       - go

    - name: Copy Bash Configuration
      copy:
        src: bash/
        dest: ~/
        mode: 0600
      tags:
        - shell

    - name: Copy SSH Configuration
      template:
        src: config.j2
        dest: ~/.ssh/config
        mode: 0600
      tags:
        - shell

    - name: Copy Git Configuration
      template:
        src: .gitconfig.j2
        dest: ~/.gitconfig
        mode: 0600
      tags:
        - vcs

    - name: Copy Mecurial Configuration
      template:
        src: .hgrc.j2
        dest: ~/.hgrc
        mode: 0600
      tags:
        - vcs

    - name: Copy SleepWatcher Configuration
      template:
        src: "{{ item }}"
        dest: ~/{{ item | basename | regex_replace('\.j2','') }}
        mode: 0744
      with_items:
        - sleepwatcher/.sleep.j2
        - sleepwatcher/.wakeup.j2
      tags:
        - sleepwatcher

    - name: Start SleepWatcher Service
      shell: brew services start sleepwatcher
      become_user: "{{ ansible_user_id }}"
      tags:
        - sleepwatcher

    - name: Create SleepWatcher Log Directory
      file:
        path: "{{ sleepwatcher.log | dirname }}"
        state: directory
        mode: 0751
      tags:
        - sleepwatcher

    - name: Create SleepWatcher Log File
      file:
        path: "{{ sleepwatcher.log }}"
        state: touch
        mode: 0644
      tags:
        - sleepwatcher

    - name: Check Photo Library Exists
      stat:
        path: "~/Pictures/Photos Library.photoslibrary/Masters/"
      register: photo_library
      tags:
        - photos

    - name: Symlink Photos Library
      file:
        src: "~/Pictures/Photos Library.photoslibrary/Masters/"
        dest: "~/Pictures/Photos Library Raw"
        state: link
      when: photo_library.stat.exists
      tags:
        - photos

    - name: Install Custom Fonts
      copy:
        src: fonts/
        dest: ~/Library/Fonts
        mode: 0755
      tags:
        - fonts

    - name: Update Hosts
      blockinfile:
        dest: /etc/hosts
        marker: '# {mark} Security'
        backup: yes
        content: "{{ lookup('file', 'hosts') }}"
      become: yes
      tags:
        - hosts

    - name: Reload Hosts
      shell: dscacheutil -flushcache && killall -HUP mDNSResponder
      ignore_errors: yes
      tags:
        - hosts

    - name: Copy Mac OS Script
      template:
        src: .macos.j2
        dest: /tmp/macos.sh
        mode: 0700
      tags:
        - macos

    - name: Run Mac OS Script
      shell: /bin/bash /tmp/macos.sh
      tags:
        - macos

    - name: Remove Mac OS Script
      file:
        path: /tmp/macos.sh
        state: absent
      tags:
        - macos

    - name: Homebrew Cleanup
      shell: brew cleanup && brew prune
      tags:
        - homebrew
