---
- hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: Install Shell Enhancements
      homebrew:
        name: bash-completion
        state: latest

    - name: Install VCS
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - mercurial
        - svn

    - name: Install Utilities
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - tree
        - ncdu
        - mosh
        - ack
        - p7zip
        - archey
        - neofetch
        - httpie
        - sleepwatcher
        - tmux

    - name: Install WGet
      homebrew:
        name: wget
        options: with-iri
        state: latest

    - name: Install Cask Applications
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - keepingyouawake

    - name: Install RBEnv
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - ruby-build
        - rbenv

    - name: Install Ruby
      shell: rbenv install --skip-existing {{ ruby_version }} && rbenv global {{ ruby_version }}

    - name: Copy Bash Configuration
      copy:
        src: bash/
        dest: ~/
        mode: 0600

    - name: Copy SSH Configuration
      template:
        src: config.j2
        dest: ~/.ssh/config
        mode: 0600

    - name: Copy Git Configuration
      template:
        src: gitconfig.j2
        dest: ~/.gitconfig
        mode: 0600

    - name: Copy Mecurial Configuration
      template:
        src: hgrc.j2
        dest: ~/.hgrc
        mode: 0600

    - name: Check Photo Library Exists
      stat:
        path: "~/Pictures/Photos Library.photoslibrary/Masters/"
      when: symlink_photos
      register: photo_library

    - name: Symlink Photos Library
      file:
        src: "~/Pictures/Photos Library.photoslibrary/Masters/"
        dest: "~/Pictures/Photos Library Raw"
        state: link
      when: symlink_photos and photo_library.stat.exists

    - name: Update Hosts
      blockinfile:
        dest: /etc/hosts
        marker: '# {mark} Security'
        backup: yes
        content: "{{ lookup('file', 'hosts') }}"
      become: yes

    - name: Reload Hosts
      shell: dscacheutil -flushcache && killall -HUP mDNSResponder
      ignore_errors: yes

    - name: Homebrew Cleanup
      shell: brew cleanup && brew prune
