---
- name: Update Hosts
  blockinfile:
    dest: /etc/hosts
    marker: '# {mark} Security'
    backup: yes
    content: "{{ lookup('file', 'hosts') }}"
  become: yes
  tags:
    - hosts
    - security

- name: Reload Hosts
  shell: dscacheutil -flushcache && killall -HUP mDNSResponder
  ignore_errors: yes
  tags:
    - hosts
    - security
