# @see: https://thoughtbot.com/blog/brewfile-a-gemfile-but-for-homebrew
# @see: https://github.com/pndurette/mac-setup/blob/master/.Brewfile

# Taps
tap "beeftornado/rmtree"
tap "github/gh"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "shivammathur/php"

# Utilities
brew "ansible"
brew "ansible-lint"
brew "archey"
brew "bash-completion"
brew "bat"
brew "exa"
brew "fdupes"
brew "ffmpeg"
brew "gh"
brew "git"
brew "htop"
brew "httpie"
brew "jhead"
brew "jless"
brew "jq"
brew "libav"
brew "monolith"
brew "neofetch"
brew "ncdu"
brew "nmap"
brew "p7zip"
brew "packer"
brew "rename"
brew "rmtree"
brew "tmux"
brew "trash"
brew "tree"
brew "youtube-dl"
brew "zsh-autosuggestions"

# GNU
brew "ack"
brew "findutils"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnutls"
brew "grep"
brew "coreutils"
brew "binutils"
brew "diffutils"
brew "gzip"
brew "watch"
brew "tmux"
brew "wget"

# Languages
brew "deno"
brew "go"
brew "goreleaser"
brew "node"
brew "php"
brew "yarn"

# Casks
cask "balenaetcher"
cask "calibre"
cask "cyberduck"
cask "docker"
cask "dropbox"
cask "filebot"
cask "firefox"
cask "github"
cask "google-chrome"
cask "handbrake"
cask "imageoptim"
cask "java"
cask "kap"
cask "lulu"
cask "keepingyouawake"
cask "mullvadvpn"
cask "namechanger"
cask "pika"
cask "phpstorm"
cask "rectangle"
cask "spotify"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "tableplus"
cask "the-unarchiver"
cask "transmission"
cask "transmit"
cask "vagrant"
cask "vlc"
cask "virtualbox"
cask "virtualbox-extension-pack"

# AppStore
brew "mas"
mas "iA Writer Classic", id: 439623248
mas "Magnet", id: 441258766
mas "ToothFairy", id: 1191449274
mas "TrashMe 3", id: 1490879410

# AppStore Apple
mas "Pages", id: 409201541
mas "Numbers", id: 409203825
mas "Keynote", id: 409183694
